language: node_js
node_js:
  - "0.8"
before_install:
  # http://ninja.sg/casperjs-travis-ci/
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.0.2
  - export PATH=$PATH:`pwd`/bin
  - cd -
before_script:
  - phantomjs --version
  - casperjs --version
secure: "LDKPc9w38HEXA6GH65w9gOZau2vXdSz+ir8W69YPNYwaLfwwIlURzt22lXNs\nhVnZxAuFZP+s1SMexl2Hascrtdn68bkVq+V/pBFv5PmB8FqNUnOcxm1otKOl\nWF7Wf5IKYfIe4F+N2m72Ap59M8Pkk5dEmsD0P70koDUxQ6zPVME="