language: node_js
node_js:
  - "0.8"
before_install:
  # http://ninja.sg/casperjs-travis-ci/
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.0.2
  - export PATH=$PATH:`pwd`/bin
  - cd -
before_script:
  - phantomjs --version
  - casperjs --version
env:
  global:
    # rum_aum_username
    - secure: "goDyVfc7wD/q8IKx819ZEmSzmTw0BpZJuCjO2KcKDTU6TJXcqyKR/YklXFI5\nCPykg35GZQkk3TqvjWsafMThZGEMlmx8z4KPWxizkN9/2RNoOUv5rEbNYOmz\n3R7VThablPmXudecVKJftzDNdkL95DCY3Tw9Fq5b7hGdN9wthW0="
    # rum_aum_password
    - secure: "FqLqE57mujY3w2pG7pcb9+qSYXB+glLTEuYYIovSCF3CymmAVt5v7DazoSWE\nrZjq6ZVQXhHm9e+7S9FWD0w+oQjWpM+TxgHphLwkZDshPNQNbS9UnIhf9KgO\nAP1+J0c9ekOIwYjSrv1pNy2mR/I7buE6Dz05Homkm+t2qoz1JmI="